# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'focus-mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 551))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 100, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 140, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 180, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 510, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 661, 541))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 10, 251, 181))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(820, 190, 251, 181))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Screenshot 2022-210-02 141600.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.histogram = QtWidgets.QLabel(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(820, 40, 251, 131))
        self.histogram.setAutoFillBackground(False)
        self.histogram.setText("")
        self.histogram.setPixmap(QtGui.QPixmap("Screenshot 2022-10-02 150511.png"))
        self.histogram.setScaledContents(True)
        self.histogram.setObjectName("histogram")
        self.histogram.setVisible(False)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(820, 380, 251, 181))
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setVisible(False)
        self.label_2.setVisible(False)
        self.label_3.setVisible(False)
        self.histogramLabel = QtWidgets.QLabel(self.centralwidget)
        self.histogramLabel.setGeometry(QtCore.QRect(910, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.histogramLabel.setFont(font)
        self.histogramLabel.setObjectName("label")
        self.histogramLabel.setVisible(False)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave_as = QtWidgets.QMenu(self.menuFile)
        self.menuSave_as.setObjectName("menuSave_as")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCube = QtWidgets.QAction(MainWindow)
        self.actionCube.setObjectName("actionCube")
        self.menuSave_as.addAction(self.actionCube)
        self.menuFile.addAction(self.menuSave_as.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def focusMode(self, MainWindow):
        self.cancel(MainWindow)
        self.label.setVisible(True)
        self.label_2.setVisible(True)
        self.label_3.setVisible(True)
        self.textEdit.setText("Sharpness: 5\r\nSharpness:4\r\nSharpness:11\r\nSharpness: 5\r\nSharpness:4\r\nSharpness:11\r\nSharpness: 5\r\nSharpness:4\r\nSharpness:11\r\nSharpness: 5\r\nSharpness:4\r\nSharpness:11\r\nSharpness: 5\r\nSharpness:4\r\nSharpness:11\r\n")

    def captureMode(self, MainWindow):
        self.cancel(MainWindow)
        self.label.setVisible(True)
        self.histogram.setVisible(True)
        self.histogramLabel.setVisible(True)
        self.label_3.setVisible(True)
        self.textEdit.setText("Imaging...\r\n365nm captured\r\n385nm captured")



    def cancel(self, MainWindow):
        self.label.setVisible(False)
        self.label_2.setVisible(False)
        self.label_3.setVisible(False)
        self.textEdit.setText("")
        self.histogram.setVisible(False)
        self.histogramLabel.setVisible(False)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MISHA Image Capture"))
        self.groupBox.setTitle(_translate("MainWindow", "Operations"))
        self.pushButton.setText(_translate("MainWindow", "Focus"))
        self.pushButton.clicked.connect(self.focusMode)
        self.pushButton_2.setText(_translate("MainWindow", "Capture Images"))
        self.pushButton_2.clicked.connect(self.captureMode)
        self.pushButton_3.setText(_translate("MainWindow", "Capture Flats"))
        self.pushButton_4.setText(_translate("MainWindow", "Test LEDs"))
        self.pushButton_5.setText(_translate("MainWindow", "Light Levels"))
        self.pushButton_6.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_6.clicked.connect(self.cancel)
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/Screenshot 2022-10-02 141047.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/Screenshot 2022-10-02 141600.png\"/><img src=\":/images/Screenshot 2022-10-02 141600.png\"/></p></body></html>"))
        self.histogramLabel.setText(_translate("MainWindow", "Histogram"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave_as.setTitle(_translate("MainWindow", "Save as..."))
        self.actionCube.setText(_translate("MainWindow", "Cube"))


import resources_rc, sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

